- name: stop nginx
  become: yes
  service: name=nginx state=stopped

- name: kill certbot-nginx
  become: yes
  shell: killall nginx

- name: start nginx
  become: yes
  service: name=nginx state=started
