- name: install certbot
  become: yes
  apt:
    name:
      - certbot
      - python-certbot-nginx
  notify:
    - stop nginx

- name: stop nginx
  become: yes
  service: name=nginx state=stopped

- name: register certs
  become: yes
  shell: certbot --nginx -d {{ certdomains }} -n --agree-tos --redirect -m h0wy36@gmail.com

- name: kill certbot nginx
  become: yes
  shell: killall nginx

- name: start nginx
  become: yes
  service: name=nginx state=started
