ALTER TABLE REPORTS.RUN
    ADD DISTRO VARCHAR(40),
    ADD DISTRO_VERSION VARCHAR(40),

    ADD KERNEL_VERSION VARCHAR(40),

    ADD TARGET VARCHAR(20);

ALTER TABLE REPORTS.COMPILER
    ADD VERSION VARCHAR(20);
