global:
    scrape_interval: 5m
    evaluation_interval: 5m

scrape_configs:
    - job_name: 'prometheus'
      scrape_interval: 2m
      scrape_timeout: 5s
      static_configs: ['localhost:9090']
    - job_name: 'postgres'
      scrape_interval: 2m
      scrape_timeout: 5s
    - job_name: 'node'
      static_configs:
          - targets: ['localhost:9100']
