logging:
  level: DEBUG

  loggers:
    "org.eclipse": INFO

reportDatabase:
  driverClass: org.postgresql.Driver
  user: postgres
  password: admin
  url: jdbc:postgresql://25.57.48.59/reports

gitHooksDatabase:
  driverClass: org.postgresql.Driver
  user: postgres
  password: admin
  url: jdbc:postgresql://25.57.48.59/githooks
