logging:
  level: DEBUG

  loggers:
    "org.eclipse": INFO

flyway:
  sqlMigrationPrefix: v
  sqlMigrationSeparator: "-"
  schemas:
    - reports
    - githooks

reportDatabase:
  driverClass: org.postgresql.Driver
  user: postgres
  password: admin
  url: jdbc:postgresql://25.57.48.59/kafei

gitHooksDatabase:
  driverClass: org.postgresql.Driver
  user: postgres
  password: admin
  url: jdbc:postgresql://25.57.48.59/kafei

crashDatabase:
  driverClass: org.postgresql.Driver
  user: postgres
  password: admin
  url: jdbc:postgresql://25.57.48.59/kafei

corsData:
  allowOrigin: "http://localhost:8080"