server:
  applicationConnectors:
  - type: http
    port: 8040
  adminConnectors:
  - type: http
    port: 8041

reportDatabase:
  driverClass: org.postgresql.Driver
  user: postgres
  password: postgres
  url: jdbc:postgresql://localhost/reports

gitHooksDatabase:
  driverClass: org.postgresql.Driver
  user: postgres
  password: postgres
  url: jdbc:postgresql://localhost/githooks
