server:
  applicationConnectors:
  - type: http
    port: 8040
  adminConnectors:
  - type: http
    port: 8041

flyway:
  sqlMigrationPrefix: v
  sqlMigrationSeparator: "-"
  schemas:
    - reports
    - githooks

reportDatabase:
  driverClass: org.postgresql.Driver
  user: postgres
  password: postgres
  url: jdbc:postgresql://localhost/kafei

gitHooksDatabase:
  driverClass: org.postgresql.Driver
  user: postgres
  password: postgres
  url: jdbc:postgresql://localhost/kafei

crashDatabase:
  driverClass: org.postgresql.Driver
  user: postgres
  password: postgres
  url: jdbc:postgresql://localhost/kafei

corsData:
  allowOrigin: "*"
  allowMethods: "OPTIONS,GET,POST"