- name: install nginx
  become: yes
  apt:
    name:
      - nginx
      - certbot
      - nginx-extras

- name: add configuration
  become: yes
  copy: src=nginx.conf dest=/etc/nginx/nginx.conf mode=644

- name: create streams-enabled directory
  become: yes
  file: path=/etc/nginx/streams-enabled state=directory mode=755

- name: create applications-enabled directory
  become: yes
  file: path=/etc/nginx/applications-enabled state=directory mode=755

- name: add site configs
  become: yes
  template: src={{item}}.conf dest=/etc/nginx/sites-available/{{item}}.conf mode=644
  with_items:
    - '10-kafei'
    - '20-shortener'
    - '50-dash-http'

- name: disable default
  become: yes
  file: path=/etc/nginx/sites-enabled/default state=absent

- name: enable sites
  become: yes
  file:
      src: /etc/nginx/sites-available/{{ item }}.conf
      dest: /etc/nginx/sites-enabled/{{ item }}.conf
      state: link
  with_items:
    - '10-kafei'
    - '20-shortener'
    - '50-dash-http'
  notify:
    - restart nginx

- name: add stream configs
  become: yes
  template: src={{item}}.conf dest=/etc/nginx/streams-enabled/{{item}}.conf mode=644
  with_items: []

- name: add application configs
  become: yes
  template: src={{item}}.conf dest=/etc/nginx/applications-enabled/{{item}}.conf mode=644
  with_items:
    - '50-dash-rtmp'

- name: make video serving directory
  become: yes
  file: path={{ dataroot }}/video state=directory owner=ubuntu mode=755
