---

- name: set config
  hosts: webservers
  vars:
    hostname: kafei
  roles:
    - config

- name: configure server
  hosts: webservers
  roles:
    - nginx
    - jdk
    - mosquitto
    - postgres
    - prometheus

