- name: copying backup to server
  copy: src={{ db }}_dump.sql.gz dest=/tmp/{{ db }}_dump.sql.gz mode=666

- name: 'restoring database {{ db }}'
  become: yes
  become_user: '{{ db }}'
  postgresql_db:
    name: '{{ db }}'
    state: restore
    target: /tmp/{{ db }}_dump.sql.gz
    login_user: kafei
