CREATE TABLE RATES(
    IP VARCHAR(15) PRIMARY KEY NOT NULL,
    REQUESTS INTEGER NOT NULL
);

CREATE TABLE RUN(
    RUN_ID SERIAL PRIMARY KEY NOT NULL,
    BUILD_VERSION VARCHAR(30) NOT NULL,
    CWD VARCHAR(255) NOT NULL,
    MEMORY BIGINT NOT NULL,
    SWAPSPACE BIGINT NOT NULL,
    SWAPSPACE_FREE BIGINT NOT NULL,
    SYSTEM VARCHAR(80) NOT NULL,
    SUBMIT_TIME TIMESTAMP NOT NULL,
    COMMANDLINE VARCHAR(255) NOT NULL
);

CREATE TABLE ARCHITECTURE(
    ARCH_NAME VARCHAR(30) PRIMARY KEY NOT NULL
);

CREATE TABLE COMPILER(
    COMPILER_NAME VARCHAR(30) PRIMARY KEY NOT NULL
);

CREATE TABLE APPLICATION(
    APP_ID SERIAL PRIMARY KEY,
    APP_NAME VARCHAR(50) NOT NULL,
    APP_ORG VARCHAR(50) NOT NULL,
    APP_VERSION INTEGER NOT NULL,
    CONSTRAINT APP_UQ UNIQUE (APP_NAME, APP_ORG, APP_VERSION)
);

CREATE TABLE PROCESSOR(
    PROC_ID SERIAL PRIMARY KEY,
    PROC_MANUFACTURER VARCHAR(20) NOT NULL,
    PROC_NAME VARCHAR(80) NOT NULL,
    PROC_HYPERTHREADING BOOL NOT NULL,
    PROC_FPU BOOL NOT NULL,
    PROC_PAE BOOL NOT NULL,
    PROC_THREADS INTEGER NOT NULL,
    PROC_CORES INTEGER NOT NULL,
    CONSTRAINT PROC_UQ UNIQUE (PROC_MANUFACTURER, PROC_NAME)
);

CREATE TABLE PROCESSOR_FREQ(
    PROC_ID SERIAL REFERENCES PROCESSOR ON DELETE CASCADE,
    PROC_FREQ REAL NOT NULL,
    PRIMARY KEY (PROC_ID, PROC_FREQ)
);

CREATE TABLE PROCESSOR_FW(
    PROC_ID SERIAL REFERENCES PROCESSOR ON DELETE CASCADE,
    PROC_FW VARCHAR(8) NOT NULL,
    PRIMARY KEY (PROC_ID, PROC_FW)
);

CREATE TABLE DEVICE(
    DEV_ID SERIAL PRIMARY KEY,
    DEV_NAME VARCHAR(80) NOT NULL,
    DEV_MOTHERBOARD VARCHAR(80) NOT NULL,
    DEV_CHASSIS VARCHAR(80) NOT NULL,
    DEV_PLATFORM INTEGER NOT NULL,
    DEV_TYPE INTEGER NOT NULL,
    DEV_DPI REAL NOT NULL,
    CONSTRAINT DEVICE_UQ UNIQUE (DEV_NAME, DEV_MOTHERBOARD, DEV_CHASSIS, DEV_TYPE, DEV_DPI)
);

CREATE TABLE RUN_ARCH(
    RUN_ID SERIAL REFERENCES RUN ON DELETE CASCADE, 
    ARCH_NAME VARCHAR(30) REFERENCES ARCHITECTURE ON DELETE CASCADE,
    PRIMARY KEY (RUN_ID, ARCH_NAME)
);

CREATE TABLE RUN_COMPILER(
    RUN_ID SERIAL REFERENCES RUN ON DELETE CASCADE,
    COMPILER_NAME VARCHAR(30) REFERENCES COMPILER ON DELETE CASCADE,
    PRIMARY KEY (RUN_ID, COMPILER_NAME)
);

CREATE TABLE RUN_APP(
    RUN_ID SERIAL REFERENCES RUN ON DELETE CASCADE,
    APP_ID SERIAL REFERENCES APPLICATION ON DELETE CASCADE,
    PRIMARY KEY (RUN_ID, APP_ID)
);

CREATE TABLE RUN_PROC(
    RUN_ID SERIAL REFERENCES RUN ON DELETE CASCADE,
    PROC_ID SERIAL REFERENCES PROCESSOR ON DELETE CASCADE,
    PRIMARY KEY (RUN_ID, PROC_ID)
);

CREATE TABLE RUN_DEVICE(
    RUN_ID SERIAL REFERENCES RUN ON DELETE CASCADE,
    DEV_VERSION VARCHAR(50) NOT NULL,
    DEV_ID SERIAL REFERENCES DEVICE ON DELETE CASCADE,
    PRIMARY KEY (RUN_ID, DEV_VERSION, DEV_ID)
);

