- name: install mosquitto
  become: yes
  apt: 
    name:
      - mosquitto
      - mosquitto-clients

- name: add configuration
  become: yes
  copy: src=mosquitto.conf dest=/etc/mosquitto/mosquitto.conf mode=644

- name: add access configuration
  become: yes
  template: src=access.conf dest=/etc/mosquitto/access.conf mode=644

- name: add port configuration
  become: yes
  template: src=default.conf dest=/etc/mosquitto/conf.d/default.conf mode=644

- name: stop mosquitto
  become: yes
  service: name=mosquitto state=stopped

- name: create mosquitto password file
  become: yes
  file:
    path: /etc/mosquitto/passwd
    state: touch

- name: set user passwords
  become: yes
  shell: mosquitto_passwd -b /etc/mosquitto/passwd '{{ item.name }}' '{{ item.password }}'
  with_items: '{{ mqtt.users }}'

- name: start mosquitto
  become: yes
  service: name=mosquitoo state=started
