ALTER TABLE REPORTS.RUN_COMPILER
    DROP CONSTRAINT run_compiler_pkey,
    ADD VERSION VARCHAR(20) NOT NULL DEFAULT '0.0.0',
    ADD CONSTRAINT RUN_COMPILER_PK PRIMARY KEY (RUN_ID, COMPILER_NAME, VERSION);