FROM alpine:latest

RUN apk update && apk add python3-dev py-virtualenv bash build-base postgresql-dev libffi-dev

RUN mkdir -p /workdir && \
	cd /workdir && \
	python3.6 -m venv kafei_py

WORKDIR /workdir
CMD ["bash", "-c", ". kafei_py/bin/activate && pip3 install -r /pyapp/requirements.txt && python3 /pyapp/$PYAPP_NAME"]

