name: Svelte
on: push
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2-beta
      with:
        node-version: '12'
    - name: Checkout source
      uses: actions/checkout@v2
    - name: Install dependencies
      run: npm install
      working-directory: services/kafei/client
    - name: Build Svelte app
      run: npm run build
      working-directory: services/kafei/client

