name: Backend build
on: push
jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        jdk-ver: [8, 9]
    steps:
    - name: Checkout source
      uses: actions/checkout@v2
    - name: Setup Java ${{ matrix.jdk-ver }}
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.jdk-ver }}
    - name: Gradle build
      uses: eskatos/gradle-command-action@v1
      with:
        wrapper-directory: services/kafei
        arguments: :assemble
        wrapper-cache-enabled: true
        dependencies-cache-enabled: true
        configuration-cache-enabled: true

